---
# a comment
- name: Configure Server For Telegraf
  hosts: all:!localhost

  tasks:
    - name: Create InfluxData Repo (Bionic)
      lineinfile:
        path: /etc/apt/sources.list.d/influxdata.list
        create: yes
        owner: root
        group: root
        mode: 0644
        state: present
        line: 'deb https://repos.influxdata.com/ubuntu bionic stable'
      when: ansible_distribution_release == "bionic"
    - name: Install telegraf
      apt:
        name: telegraf
        update_cache: yes
      register: telegraf.installed
      when: ansible_distribution_release == "bionic"
    - name: Download Config File If Telegraf Got Installed
      get_url:
        url: https://raw.githubusercontent.com/dison4linux/ansible-awx/master/files/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
        mode: 0644
      when: telegraf.installed.changed
    - name: Restart Telegraf if necessary
      service:
        name: telegraf
        state: restarted
      when: telegraf.installed.changed
